[theme]
# Primary colors
primaryColor = "#00d4ff"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"

# Font
font = "Inter"

[server]
# Server configuration
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "localhost"

[client]
# Client configuration
showErrorDetails = true
toolbarMode = "minimal"

[runner]
# Runner configuration
magicEnabled = true
installTracer = false
fixMatplotlib = true
