[global]
# Development mode settings
developmentMode = false

[server]
# Server configuration
port = 8501
address = "localhost"
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Theme configuration
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
# Client-side settings
showErrorDetails = true
toolbarMode = "minimal"